development:
  adapter: postgresql
  database: questions_dev
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: questions_test
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: questions_production
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost